"""users table

Revision ID: 08991f6ae389
Revises: e223fdd6544d
Create Date: 2020-04-23 21:50:53.467107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08991f6ae389'
down_revision = 'e223fdd6544d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_client_block', sa.Column('edited_time', sa.DateTime(), nullable=True))
    op.add_column('home_client_block', sa.Column('editor_user_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'home_client_block', 'admin', ['editor_user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'home_client_block', type_='foreignkey')
    op.drop_column('home_client_block', 'editor_user_id')
    op.drop_column('home_client_block', 'edited_time')
    # ### end Alembic commands ###
