"""architecture_item_block table

Revision ID: 161156650d52
Revises: 2a28de9d5a55
Create Date: 2020-12-06 13:27:59.164514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161156650d52'
down_revision = '2a28de9d5a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_item_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('editor_user_id', sa.String(length=64), nullable=True),
    sa.Column('edited_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editor_user_id'], ['admin.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('architecture_item_block')
    # ### end Alembic commands ###
