"""home_about_block table

Revision ID: 237da8bb9f81
Revises: 8d0907ba8a2b
Create Date: 2020-04-14 20:44:02.702077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237da8bb9f81'
down_revision = '8d0907ba8a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_about_block', sa.Column('link_text', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home_about_block', 'link_text')
    # ### end Alembic commands ###
