"""empty message

Revision ID: 36da325dc72c
Revises: c3aa8f9de980
Create Date: 2020-12-08 11:19:06.482854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36da325dc72c'
down_revision = 'c3aa8f9de980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learn_material_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('editor_user_id', sa.String(length=64), nullable=True),
    sa.Column('edited_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editor_user_id'], ['admin.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learn_material_block')
    # ### end Alembic commands ###
