"""home_functions_block table

Revision ID: 59c245196b28
Revises: ef53ee06afca
Create Date: 2020-04-08 16:56:58.150485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c245196b28'
down_revision = 'ef53ee06afca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_functions_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('icon', sa.String(length=256), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('editor_user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['editor_user_id'], ['admin.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_functions_block')
    # ### end Alembic commands ###
