"""home_functions_block table

Revision ID: 82acc36b9b8a
Revises: 59c245196b28
Create Date: 2020-04-09 17:15:23.069763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82acc36b9b8a'
down_revision = '59c245196b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home_functions_block', sa.Column('edited_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_home_functions_block_edited_time'), 'home_functions_block', ['edited_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_functions_block_edited_time'), table_name='home_functions_block')
    op.drop_column('home_functions_block', 'edited_time')
    # ### end Alembic commands ###
