"""home_about_block table

Revision ID: 8d0907ba8a2b
Revises: 82acc36b9b8a
Create Date: 2020-04-10 14:16:24.708949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0907ba8a2b'
down_revision = '82acc36b9b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_about_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('editor_user_id', sa.String(length=64), nullable=True),
    sa.Column('edited_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editor_user_id'], ['admin.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_home_functions_block_edited_time', table_name='home_functions_block')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_home_functions_block_edited_time', 'home_functions_block', ['edited_time'], unique=False)
    op.drop_table('home_about_block')
    # ### end Alembic commands ###
