"""empty message

Revision ID: e07d16f2c127
Revises: 36da325dc72c
Create Date: 2020-12-08 12:13:36.591654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07d16f2c127'
down_revision = '36da325dc72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learn_res_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('content', sa.String(length=1024), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('link_text', sa.String(length=64), nullable=True),
    sa.Column('editor_user_id', sa.String(length=64), nullable=True),
    sa.Column('edited_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editor_user_id'], ['admin.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learn_res_block')
    # ### end Alembic commands ###
