"""home_client_block table

Revision ID: e223fdd6544d
Revises: 237da8bb9f81
Create Date: 2020-04-20 15:01:19.957462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e223fdd6544d'
down_revision = '237da8bb9f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_client_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_logo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_client_block')
    # ### end Alembic commands ###
