"""architecture_ebook_block table

Revision ID: f99c0708a408
Revises: 161156650d52
Create Date: 2020-12-08 07:29:50.679925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99c0708a408'
down_revision = '161156650d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('architecture_ebook_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('editor_user_id', sa.String(length=64), nullable=True),
    sa.Column('edited_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['editor_user_id'], ['admin.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('architecture_ebook_block')
    # ### end Alembic commands ###
